In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
file1= "../raw_data/JC-202105-citibike-tripdata.csv"
df = pd.read_csv(file1)
df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,74A4206E7487CBC9,docked_bike,2021-05-23 16:51:00,2021-05-23 18:38:21,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,casual
1,58EEE2950FFE01CE,docked_bike,2021-05-31 16:54:47,2021-05-31 16:55:28,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,member
2,1429D912C16EEE59,docked_bike,2021-05-25 16:19:34,2021-05-25 17:03:06,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,casual
3,FE9C5B74167CBCCD,docked_bike,2021-05-22 17:32:19,2021-05-22 17:41:27,9 St HBLR - Jackson St & 8 St,HB305,Grand St & 2 St,HB405,40.747907,-74.038411,40.739130,-74.036180,casual
4,B88D37626F000BBA,docked_bike,2021-05-14 09:48:34,2021-05-14 10:17:36,Union St,JC051,Newark Ave,JC032,40.718211,-74.083639,40.721525,-74.046305,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45038,62FF3FEDAAD7FCB3,docked_bike,2021-05-31 12:46:22,2021-05-31 12:52:29,Clinton St & 7 St,HB303,7 St & Monroe St,HB304,40.745420,-74.033320,40.746413,-74.037977,casual
45039,E742AEA7068E0E4A,docked_bike,2021-05-31 16:34:19,2021-05-31 16:59:21,Clinton St & 7 St,HB303,Clinton St & 7 St,HB303,40.745420,-74.033320,40.745420,-74.033320,casual
45040,E769F9EE96D6433A,docked_bike,2021-05-17 22:52:35,2021-05-17 23:13:37,Astor Place,JC077,Astor Place,JC077,40.719282,-74.071261,40.719282,-74.071262,casual
45041,EC973614DCA179A2,docked_bike,2021-05-31 20:48:58,2021-05-31 21:16:02,Clinton St & 7 St,HB303,Clinton St & 7 St,HB303,40.745420,-74.033320,40.745420,-74.033320,casual
45042,3571180FE5C52CB1,docked_bike,2021-05-23 14:28:43,2021-05-23 14:30:59,Clinton St & 7 St,HB303,Clinton St & 7 St,HB303,40.745420,-74.033320,40.745420,-74.033320,casual

In [3]:
import glob
import os

In [5]:
files_join = os.path.join("../raw_data", "JC-20*.csv")
files_list = glob.glob(files_join)
files_list

['../raw_data\\JC-202105-citibike-tripdata.csv',
 '../raw_data\\JC-202106-citibike-tripdata.csv',
 '../raw_data\\JC-202107-citibike-tripdata.csv',
 '../raw_data\\JC-202108-citibike-tripdata.csv',
 '../raw_data\\JC-202109-citibike-tripdata.csv',
 '../raw_data\\JC-202110-citibike-tripdata.csv',
 '../raw_data\\JC-202111-citibike-tripdata.csv',
 '../raw_data\\JC-202112-citibike-tripdata.csv',
 '../raw_data\\JC-202201-citibike-tripdata.csv',
 '../raw_data\\JC-202202-citibike-tripdata.csv',
 '../raw_data\\JC-202203-citibike-tripdata.csv',
 '../raw_data\\JC-202204-citibike-tripdata.csv',
 '../raw_data\\JC-202205-citibike-tripdata.csv',
 '../raw_data\\JC-202206-citibike-tripdata.csv']

In [33]:
df = pd.concat(map(pd.read_csv, files_list), ignore_index=False)
df.reset_index()

,index,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,0,74A4206E7487CBC9,docked_bike,2021-05-23 16:51:00,2021-05-23 18:38:21,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,casual
1,1,58EEE2950FFE01CE,docked_bike,2021-05-31 16:54:47,2021-05-31 16:55:28,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,member
2,2,1429D912C16EEE59,docked_bike,2021-05-25 16:19:34,2021-05-25 17:03:06,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,casual
3,3,FE9C5B74167CBCCD,docked_bike,2021-05-22 17:32:19,2021-05-22 17:41:27,9 St HBLR - Jackson St & 8 St,HB305,Grand St & 2 St,HB405,40.747907,-74.038411,40.739130,-74.036180,casual
4,4,B88D37626F000BBA,docked_bike,2021-05-14 09:48:34,2021-05-14 10:17:36,Union St,JC051,Newark Ave,JC032,40.718211,-74.083639,40.721525,-74.046305,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943689,103294,25AD34565A260732,classic_bike,6/17/2022 16:03,6/17/2022 16:33,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,11 St & Washington St,HB502,40.736982,-74.027781,40.749985,-74.027150,casual
943690,103295,8A4181FCE9439036,classic_bike,6/25/2022 14:14,6/25/2022 14:19,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,8 St & Washington St,HB603,40.736982,-74.027781,40.745984,-74.028199,member
943691,103296,28C8501BCB596743,electric_bike,6/4/2022 8:57,6/4/2022 9:15,Jersey & 6th St,JC027,11 St & Washington St,HB502,40.725289,-74.045572,40.749985,-74.027150,casual
943692,103297,D28575BBFF3A0B57,classic_bike,6/17/2022 6:11,6/17/2022 6:21,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,11 St & Washington St,HB502,40.736982,-74.027781,40.749985,-74.027150,member
943693,103298,A914FEF9390C201C,electric_bike,6/2/2022 18:15,6/2/2022 18:20,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,11 St & Washington St,HB502,40.736982,-74.027781,40.749985,-74.027150,member

In [34]:
count = df['member_casual'].value_counts()
count

member    577053
casual    366641
Name: member_casual, dtype: int64

In [35]:
count = df['start_station_name'].value_counts()
count

Grove St PATH                                   42803
South Waterfront Walkway - Sinatra Dr & 1 St    41940
Hoboken Terminal - Hudson St & Hudson Pl        35467
Hoboken Terminal - River St & Hudson Pl         28457
Newport Pkwy                                    27378
                                                ...
Bergen Ave & Stegman St                          1263
2 St HBLR - 2 St & Marshall St                    768
Grant Ave & MLK Dr                                570
JCBS Depot                                          4
E 20 St & FDR Drive                                 1
Name: start_station_name, Length: 84, dtype: int64

In [36]:
count = df['end_station_name'].value_counts()
count

Grove St PATH                                   44811
South Waterfront Walkway - Sinatra Dr & 1 St    42482
Hoboken Terminal - Hudson St & Hudson Pl        35617
Hoboken Terminal - River St & Hudson Pl         27846
Newport Pkwy                                    27227
                                                ...
E 39 St & 2 Ave                                     1
34 Ave & 38 St                                      1
W 48 St & Rockefeller Plaza                         1
South St & Broad St                                 1
Wadsworth Ave & W 175 St                            1
Name: end_station_name, Length: 319, dtype: int64

In [40]:

df['started_at']= pd.to_datetime(df['started_at'])
df['ended_at']= pd.to_datetime(df['ended_at'])
df.dtypes

ride_id                       object
rideable_type                 object
started_at            datetime64[ns]
ended_at              datetime64[ns]
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 object
dtype: object

In [41]:
count = df['started_at'].value_counts()
count

2022-06-17 19:22:00    17
2022-06-14 18:36:00    17
2022-06-28 19:18:00    17
2022-06-30 17:56:00    16
2022-06-17 18:34:00    16
                       ..
2021-08-14 02:59:04     1
2021-08-07 01:09:59     1
2021-09-16 09:57:22     1
2022-05-24 16:56:57     1
2021-08-07 14:19:51     1
Name: started_at, Length: 850900, dtype: int64

In [42]:
count = df['ended_at'].value_counts()
count

2022-02-28 13:20:58    24
2022-04-15 16:53:26    24
2021-11-03 08:07:30    24
2022-03-16 20:09:57    18
2022-06-29 18:40:00    17
                       ..
2022-05-05 20:38:59     1
2021-10-09 20:58:51     1
2021-12-30 16:35:28     1
2022-05-15 17:38:43     1
2022-04-30 13:35:56     1
Name: ended_at, Length: 850377, dtype: int64

In [43]:
df = df.rename(columns ={"rideable_type":"bike_type", "started_at":"starting_time","ended_at":"ending_time", 
                         "start_station_name": "Starting_Station", "end_station_name":"Ending_Station", "member_casual":"Member_Type"})
df.dtypes

ride_id                     object
bike_type                   object
starting_time       datetime64[ns]
ending_time         datetime64[ns]
Starting_Station            object
start_station_id            object
Ending_Station              object
end_station_id              object
start_lat                  float64
start_lng                  float64
end_lat                    float64
end_lng                    float64
Member_Type                 object
dtype: object

In [44]:
df1 = df.set_index("ride_id")
df1

,bike_type,starting_time,ending_time,Starting_Station,start_station_id,Ending_Station,end_station_id,start_lat,start_lng,end_lat,end_lng,Member_Type
ride_id,,,,,,,,,,,,
74A4206E7487CBC9,docked_bike,2021-05-23 16:51:00,2021-05-23 18:38:21,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,casual
58EEE2950FFE01CE,docked_bike,2021-05-31 16:54:47,2021-05-31 16:55:28,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,member
1429D912C16EEE59,docked_bike,2021-05-25 16:19:34,2021-05-25 17:03:06,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,casual
FE9C5B74167CBCCD,docked_bike,2021-05-22 17:32:19,2021-05-22 17:41:27,9 St HBLR - Jackson St & 8 St,HB305,Grand St & 2 St,HB405,40.747907,-74.038411,40.739130,-74.036180,casual
B88D37626F000BBA,docked_bike,2021-05-14 09:48:34,2021-05-14 10:17:36,Union St,JC051,Newark Ave,JC032,40.718211,-74.083639,40.721525,-74.046305,casual
...,...,...,...,...,...,...,...,...,...,...,...,...
25AD34565A260732,classic_bike,2022-06-17 16:03:00,2022-06-17 16:33:00,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,11 St & Washington St,HB502,40.736982,-74.027781,40.749985,-74.027150,casual
8A4181FCE9439036,classic_bike,2022-06-25 14:14:00,2022-06-25 14:19:00,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,8 St & Washington St,HB603,40.736982,-74.027781,40.745984,-74.028199,member
28C8501BCB596743,electric_bike,2022-06-04 08:57:00,2022-06-04 09:15:00,Jersey & 6th St,JC027,11 St & Washington St,HB502,40.725289,-74.045572,40.749985,-74.027150,casual
D28575BBFF3A0B57,classic_bike,2022-06-17 06:11:00,2022-06-17 06:21:00,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,11 St & Washington St,HB502,40.736982,-74.027781,40.749985,-74.027150,member
A914FEF9390C201C,electric_bike,2022-06-02 18:15:00,2022-06-02 18:20:00,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,11 St & Washington St,HB502,40.736982,-74.027781,40.749985,-74.027150,member

In [45]:
df1.count()

bike_type           943694
starting_time       943694
ending_time         943694
Starting_Station    943694
start_station_id    943694
Ending_Station      939200
end_station_id      939200
start_lat           943694
start_lng           943694
end_lat             940776
end_lng             940776
Member_Type         943694
dtype: int64

In [58]:
df1 = df1.dropna(axis=0, how ='any')
df1.count()

bike_type           939200
starting_time       939200
ending_time         939200
Starting_Station    939200
start_station_id    939200
Ending_Station      939200
end_station_id      939200
start_lat           939200
start_lng           939200
end_lat             939200
end_lng             939200
Member_Type         939200
dtype: int64

In [59]:
count = df1['starting_time'].value_counts()
count

2022-06-28 19:18:00    17
2022-06-14 18:36:00    17
2022-06-17 19:22:00    17
2022-06-17 18:34:00    16
2022-06-13 17:55:00    16
                       ..
2021-08-04 06:37:06     1
2021-05-27 22:01:03     1
2022-05-02 17:23:21     1
2022-02-10 08:21:48     1
2021-08-07 14:19:51     1
Name: starting_time, Length: 846864, dtype: int64

In [60]:
count = df1['ending_time'].value_counts()
count

2022-02-28 13:20:58    24
2022-04-15 16:53:26    24
2022-03-16 20:09:57    18
2022-06-28 17:52:00    17
2022-06-29 18:40:00    17
                       ..
2021-06-01 18:51:49     1
2022-03-18 15:06:07     1
2021-11-22 18:32:59     1
2021-11-11 08:53:15     1
2022-04-30 13:35:56     1
Name: ending_time, Length: 846960, dtype: int64

In [63]:
count = df1['bike_type'].value_counts()
count

classic_bike     585584
electric_bike    263452
docked_bike       90164
Name: bike_type, dtype: int64

In [64]:
df.to_csv("../raw_data/combined_data/comb_tab_file.csv")